version: "3.9"

services:
    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: myDBPDO
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports:
            - "9906:3306"
        volumes:
            - ./src/database:/docker-entrypoint-initdb.d    

        networks:
          - local

    loadbalancer:
        image: nginx:latest
        container_name: loadbalancer
        ports:
            - "8082:80"
        volumes:
            - ./defaultlb.conf:/etc/nginx/conf.d/default.conf
        links:
            - web
            - web2
        networks:
          - local

    web:
        image: nginx:latest
        container_name: web
        hostname: web1
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

        depends_on:
             - db    
        stdin_open: true
        tty: true

        networks:
          - local

    web2:
        image: nginx:latest
        container_name: web2
        hostname: web2
        ports:
            - "8081:80"
        volumes:
            - ./src:/var/www/html
            - ./default2.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm2

        depends_on:
             - db    
        stdin_open: true
        tty: true

        networks:
          - local

    php-fpm:
        build: 
            context: docker/php-fpm
            dockerfile: Dockerfile1
        volumes:
            - ./src:/var/www/html
        container_name: php-fpm1
        hostname: php-fpm1

        networks:
          - local

        environment:
            - HOSTNAME=web1

    php-fpm2:
        build: 
            context: docker/php-fpm
            dockerfile: Dockerfile2
        volumes:
            - ./src:/var/www/html

        container_name: php-fpm2
        hostname: php-fpm2

        networks:
          - local

        environment:
            - HOSTNAME=web2



networks:
    local:
        driver: bridge
  