version: "3.9"

services:
    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: myDBPDO
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports:
            - "9906:3306"
        volumes:
            - ./src/database:/docker-entrypoint-initdb.d    

        networks:
          - local
    web:
        image: nginx:latest
        container_name: web
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

        depends_on:
             - db    
        stdin_open: true
        tty: true

        networks:
          - local

    web2:
        image: nginx:latest
        container_name: web2
        ports:
            - "8081:80"
        volumes:
            - ./src:/var/www/html
            - ./default2.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

        depends_on:
             - db    
        stdin_open: true
        tty: true

        networks:
          - local

    php-fpm:
        build: docker/php-fpm
        volumes:
            - ./src:/var/www/html

        networks:
          - local



networks:
    local:
        driver: bridge
  