version: "3.9"

services:
    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: myDBPDO
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=myDBPDO
        ports:
            - "9906:3306"
        volumes:
            - ./src/database:/docker-entrypoint-initdb.d    

        networks:
          - local

    db_s:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: myDBPDO
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        command: --server-id=2 --relay-log-index=relay-log.index --relay-log=relay-log --master-host=db_m --master-user=devuser --master-password=devpass --master-connect-retry=60 --replicate-do-db=myDBPDO
        depends_on:
        - db
        networks:
        - local

    loadbalancer:
        image: nginx:latest
        container_name: loadbalancer
        ports:
            - "8082:443"
        volumes:
            - ./defaultlb.conf:/etc/nginx/conf.d/default.conf
            - ./crt:/etc/nginx/ssl/crt
            - ./key:/etc/nginx/ssl/key
        links:
            - web
            - web2
        networks:
          - local

    web:
        image: nginx:latest
        container_name: web
        hostname: web1
        ports:
            - "8080:443"
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./crt:/etc/nginx/ssl/crt
            - ./key:/etc/nginx/ssl/key
        links:
            - php-fpm

        depends_on:
             - db    
        stdin_open: true
        tty: true

        networks:
          - local

    web2:
        image: nginx:latest
        container_name: web2
        hostname: web2
        ports:
            - "8081:443"
        volumes:
            - ./src:/var/www/html
            - ./default2.conf:/etc/nginx/conf.d/default.conf
            - ./crt:/etc/nginx/ssl/crt
            - ./key:/etc/nginx/ssl/key
        links:
            - php-fpm2

        depends_on:
             - db_s   
        stdin_open: true
        tty: true

        networks:
          - local

    php-fpm:
        build: 
            context: docker/php-fpm
            dockerfile: Dockerfile1
        volumes:
            - ./src:/var/www/html
        container_name: php-fpm1
        hostname: php-fpm1

        networks:
          - local

        environment:
            - HOSTNAME=web1

    php-fpm2:
        build: 
            context: docker/php-fpm
            dockerfile: Dockerfile2
        volumes:
            - ./src:/var/www/html

        container_name: php-fpm2
        hostname: php-fpm2

        networks:
          - local

        environment:
            - HOSTNAME=web2



networks:
    local:
        driver: bridge
  