USE myDBPDO;
CREATE DATABASE IF NOT EXISTS myDBPDO;

CREATE TABLE IF NOT EXISTS test_table (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO test_table (name) VALUES ('John Doe');
INSERT INTO test_table (name) VALUES ('Jane Doe');